# 读写文件

In [2]:
import torch
from torch import nn
from torch.nn import functional as F

## 保存、加载张量

使用 `torch.save` 和 `torch.load` 分别保存和加载：

In [5]:
x = torch.randn([4, 5])
torch.save(x, "x-file")
print(x)

tensor([[-1.3624, -0.6662, -2.3517,  0.0261, -0.7324],
        [ 1.8455,  0.4608, -0.3855,  1.1429, -0.3526],
        [ 0.2578,  0.3612,  0.4851, -0.3225,  0.7457],
        [-1.8319, -0.1821, -0.8958,  0.1574,  1.2175]])


In [6]:
y = torch.load("x-file")
print(y)

tensor([[-1.3624, -0.6662, -2.3517,  0.0261, -0.7324],
        [ 1.8455,  0.4608, -0.3855,  1.1429, -0.3526],
        [ 0.2578,  0.3612,  0.4851, -0.3225,  0.7457],
        [-1.8319, -0.1821, -0.8958,  0.1574,  1.2175]])


/tmp/ipykernel_553708/1252936540.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  y = torch.load("x-file")


也可以存储一个 tensor table，甚至字典也可以。

In [9]:
torch.save([x, y], "x-y-file")
x1, y1 = torch.load("x-y-file")
print(x1)
print(y1)
xy_dict = { "x": x, "y": y }
torch.save(xy_dict, "xy-dict")
xy_dict1 = torch.load("xy-dict")
print(xy_dict1)

tensor([[-1.3624, -0.6662, -2.3517,  0.0261, -0.7324],
        [ 1.8455,  0.4608, -0.3855,  1.1429, -0.3526],
        [ 0.2578,  0.3612,  0.4851, -0.3225,  0.7457],
        [-1.8319, -0.1821, -0.8958,  0.1574,  1.2175]])
tensor([[-1.3624, -0.6662, -2.3517,  0.0261, -0.7324],
        [ 1.8455,  0.4608, -0.3855,  1.1429, -0.3526],
        [ 0.2578,  0.3612,  0.4851, -0.3225,  0.7457],
        [-1.8319, -0.1821, -0.8958,  0.1574,  1.2175]])
{'x': tensor([[-1.3624, -0.6662, -2.3517,  0.0261, -0.7324],
        [ 1.8455,  0.4608, -0.3855,  1.1429, -0.3526],
        [ 0.2578,  0.3612,  0.4851, -0.3225,  0.7457],
        [-1.8319, -0.1821, -0.8958,  0.1574,  1.2175]]), 'y': tensor([[-1.3624, -0.6662, -2.3517,  0.0261, -0.7324],
        [ 1.8455,  0.4608, -0.3855,  1.1429, -0.3526],
        [ 0.2578,  0.3612,  0.4851, -0.3225,  0.7457],
        [-1.8319, -0.1821, -0.8958,  0.1574,  1.2175]])}


/tmp/ipykernel_553708/327602738.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  x1, y1 = torch.load("x-y-file")
/tmp/ipykernel_553708/327602738.py:7: FutureWarning: You 

## 加载、保存模型参数

In [10]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

使用 `torch.save` 和 `state_dict` 方法保存模型参数：

In [11]:
torch.save(net.state_dict(), "mlp-params")

使用 `load_state_dict` 方法加载参数：

In [12]:
clone = MLP()
clone.load_state_dict(torch.load('mlp-params'))
clone.eval()

/tmp/ipykernel_553708/749413520.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  clone.load_state_dict(torch.load('mlp-params'))


MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

## 同时加载、保存模型参数和架构

使用 `torch.save` 直接保存模型：

In [14]:
torch.save(net, "mlp.pt")
clone2 = torch.load("mlp.pt")
clone2.eval()

/tmp/ipykernel_553708/2145624085.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  clone2 = torch.load("mlp.pt")


MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)